import { describe, it, expect, vi, beforeEach } from 'vitest';
import { BattleService } from '../src/services/battle.service';
import { LootService } from '../src/services/loot.service';
import { CombatEngine } from '@nvg/shared/src/gameLogic/CombatEngine';

// Mock Prisma
const mockUpsert = vi.fn();
const mockFindUnique = vi.fn();
const mockMobFindUnique = vi.fn();

vi.mock('../src/index', () => ({
  prisma: {
    dungeonLevel: {
      findUnique: (...args: any) => mockFindUnique(...args),
    },
    accomplishment: {
      upsert: (...args: any) => mockUpsert(...args),
    },
    character: {
      findUnique: vi.fn(),
      update: vi.fn(),
    },
    mob: {
      findUnique: (...args: any) => mockMobFindUnique(...args),
    },
  },
}));

// Mock LootService
vi.mock('../src/services/loot.service', () => ({
  LootService: {
    resolveDropTable: vi.fn(),
    awardLootToCharacter: vi.fn(),
    awardLootResultToCharacter: vi.fn(),
    mergeLoot: vi.fn((acc, loot) => {
      acc.sol += loot.sol;
      acc.items.push(...loot.items);
    }),
  },
}));

// Mock CombatEngine
vi.mock('@nvg/shared/src/gameLogic/CombatEngine', () => ({
  CombatEngine: {
    generateMobAction: vi.fn().mockReturnValue('Attack'),
  },
}));

describe('BattleService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('generateInitialMobsState', () => {
    it('should map dungeon level mobs to battle mobs and set intended actions', () => {
      const mockMobs = [
        {
          id: 'dlm_1',
          mob: {
            id: 'mob_1',
            name: 'Slime',
            level: 1,
            health: 20,
            attack: 5,
            defense: 2,
            attackPercentage: 70,
            defendPercentage: 30,
            animations: {},
          },
        },
      ];
      const rngSeed = 'test_seed';

      const result = BattleService.generateInitialMobsState(mockMobs, rngSeed);

      expect(result).toHaveLength(1);
      expect(result[0]).toMatchObject({
        id: 'dlm_1',
        name: 'Slime',
        health: 20,
        intendedAction: 'Attack',
      });
      expect(CombatEngine.generateMobAction).toHaveBeenCalled();
    });
  });

  describe('buildBattleState', () => {
    it('should correctly build a BattleState object', () => {
      const mockBattle = {
        id: 'battle_1',
        characterId: 'char_1',
        dungeonLevelId: 'dl_1',
        mobsState: [],
        round: 1,
        turn: 'PLAYER',
        status: 'IN_PROGRESS',
        rngSeed: 'seed',
      };
      const mockCharacter = {
        health: 80,
        maxHealth: 100,
      };

      const result = BattleService.buildBattleState(mockBattle, mockCharacter);

      expect(result).toEqual({
        id: 'battle_1',
        characterId: 'char_1',
        dungeonLevelId: 'dl_1',
        playerHealth: 80,
        playerMaxHealth: 100,
        mobs: [],
        round: 1,
        turn: 'PLAYER',
        status: 'IN_PROGRESS',
        rngSeed: 'seed',
      });
    });

    it('should generate intendedAction fallback if missing in mobsState', () => {
      const mockBattle = {
        id: 'battle_1',
        characterId: 'char_1',
        dungeonLevelId: 'dl_1',
        mobsState: [
          { id: 'm1', name: 'Slime', health: 10, maxHealth: 20 }
        ],
        round: 1,
        turn: 'PLAYER',
        status: 'IN_PROGRESS',
        rngSeed: 'seed',
      };
      const mockCharacter = {
        health: 80,
        maxHealth: 100,
      };

      const result = BattleService.buildBattleState(mockBattle, mockCharacter);
      expect(result.mobs[0].intendedAction).toBe('Attack'); // generated by mocked CombatEngine
    });
  });

  describe('processVictory', () => {
    beforeEach(() => {
      // Setup default mock implementations for LootService calls inside awardAfterCombatLoot
      vi.mocked(LootService.resolveDropTable).mockResolvedValue({ sol: 10, experience: 0, items: [] });
      vi.mocked(LootService.awardLootResultToCharacter).mockImplementation((charId, loot) => Promise.resolve(loot));
    });

    it('should award level loot and record level accomplishment for intermediate level', async () => {
      const mockBattle = { dungeonLevelId: 'dl_1' };
      const characterId = 'char_1';
      const lootResults = { sol: 0, experience: 0, items: [] };
      const newState: any = { status: 'VICTORY', mobs: [] };

      mockFindUnique.mockResolvedValue({
        id: 'dl_1',
        completionDropTable: { id: 'dt_level' },
        dungeon: {
          id: 'dungeon_1',
          levels: [
            { id: 'dl_1', orderIndex: 0 },
            { id: 'dl_2', orderIndex: 1 },
          ],
        },
      });

      await BattleService.processVictory(mockBattle, characterId, lootResults, newState);

      expect(LootService.resolveDropTable).toHaveBeenCalledWith('dt_level');
      expect(LootService.awardLootResultToCharacter).toHaveBeenCalledWith(characterId, expect.objectContaining({
        sol: 10
      }));
      expect(mockUpsert).toHaveBeenCalledWith(expect.objectContaining({
        create: expect.objectContaining({ type: 'DUNGEON_LEVEL_CLEARED', referenceId: 'dl_1' })
      }));
      expect(newState.nextDungeonLevelId).toBe('dl_2');
      expect(newState.isDungeonComplete).toBe(false);
      expect(lootResults.sol).toBe(10);
    });

    it('should award dungeon loot and record dungeon accomplishment for last level', async () => {
      const mockBattle = { dungeonLevelId: 'dl_2' };
      const characterId = 'char_1';
      const lootResults = { sol: 0, experience: 0, items: [] };
      const newState: any = { status: 'VICTORY', mobs: [] };

      mockFindUnique.mockResolvedValue({
        id: 'dl_2',
        completionDropTable: { id: 'dt_level' },
        dungeon: {
          id: 'dungeon_1',
          completionDropTable: { id: 'dt_dungeon' },
          levels: [
            { id: 'dl_1', orderIndex: 0 },
            { id: 'dl_2', orderIndex: 1 },
          ],
        },
      });

      vi.mocked(LootService.resolveDropTable)
        .mockResolvedValueOnce({ sol: 10, experience: 0, items: [] }) // Level loot
        .mockResolvedValueOnce({ sol: 50, experience: 0, items: [] }); // Dungeon loot

      await BattleService.processVictory(mockBattle, characterId, lootResults, newState);

      expect(LootService.resolveDropTable).toHaveBeenCalledTimes(2);
      expect(LootService.resolveDropTable).toHaveBeenNthCalledWith(1, 'dt_level');
      expect(LootService.resolveDropTable).toHaveBeenNthCalledWith(2, 'dt_dungeon');
      
      expect(mockUpsert).toHaveBeenCalledTimes(2);
      expect(mockUpsert).toHaveBeenNthCalledWith(2, expect.objectContaining({
        create: expect.objectContaining({ type: 'DUNGEON_CLEARED', referenceId: 'dungeon_1' })
      }));
      
      expect(newState.nextDungeonLevelId).toBeNull();
      expect(newState.isDungeonComplete).toBe(true);
      expect(lootResults.sol).toBe(60);
    });
  });

  describe('awardAfterCombatLoot', () => {
    const characterId = 'char_1';

    it('should aggregate loot from defeated mobs and level/dungeon completion', async () => {
      // Mock prisma.mob.findUnique
      mockMobFindUnique.mockResolvedValue({
        id: 'mob_1',
        dropTable: { id: 'dt_mob' }
      });

      // Mock prisma.dungeonLevel.findUnique
      mockFindUnique.mockResolvedValue({
        id: 'dl_1',
        completionDropTable: { id: 'dt_level' },
        dungeon: {
          id: 'dungeon_1',
          levels: [{ id: 'dl_1', orderIndex: 0 }],
          completionDropTable: { id: 'dt_dungeon' }
        }
      });

      // Mock LootService
      vi.mocked(LootService.resolveDropTable).mockImplementation((dtId: string) => {
        if (dtId === 'dt_mob') return Promise.resolve({ sol: 5, experience: 0, items: [] });
        if (dtId === 'dt_level') return Promise.resolve({ sol: 10, experience: 0, items: [] });
        if (dtId === 'dt_dungeon') return Promise.resolve({ sol: 20, experience: 0, items: [] });
        return Promise.resolve({ sol: 0, experience: 0, items: [] });
      });

      vi.mocked(LootService.awardLootResultToCharacter).mockImplementation((charId, loot) => {
        return Promise.resolve(loot);
      });

      const mobsState = [{ mobId: 'mob_1', health: 0 }];
      const result = await BattleService.awardAfterCombatLoot(characterId, 'dl_1', mobsState);

      expect(LootService.resolveDropTable).toHaveBeenCalledWith('dt_mob');
      expect(LootService.resolveDropTable).toHaveBeenCalledWith('dt_level');
      expect(LootService.resolveDropTable).toHaveBeenCalledWith('dt_dungeon');
      expect(LootService.awardLootResultToCharacter).toHaveBeenCalledWith(characterId, expect.objectContaining({
        sol: 35
      }));
      expect(result.sol).toBe(35);
    });
  });
});
